name: itslivetools_env
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.3.1=pyhd8ed1ab_0
  - aiobotocore=2.3.3=pyhd8ed1ab_0
  - aiohttp=3.8.1=py310h1961e1f_1
  - aioitertools=0.10.0=pyhd8ed1ab_0
  - aiosignal=1.2.0=pyhd8ed1ab_0
  - alabaster=0.7.12=py_0
  - anyio=3.6.1=py310h2ec42d9_0
  - aom=3.3.0=h96cf925_1
  - appdirs=1.4.4=pyh9f0ad1d_0
  - appnope=0.1.3=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py310h1961e1f_2
  - asciitree=0.3.3=py_2
  - asttokens=2.0.5=pyhd8ed1ab_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=21.4.0=pyhd8ed1ab_0
  - babel=2.10.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.1=pyha770c72_0
  - bleach=5.0.0=pyhd8ed1ab_0
  - blosc=1.21.1=h97e831e_3
  - bokeh=2.4.3=py310h2ec42d9_0
  - boost-cpp=1.74.0=hdbf7018_7
  - botocore=1.24.21=pyhd8ed1ab_1
  - branca=0.5.0=pyhd8ed1ab_0
  - brotli=1.0.9=h5eb16cf_7
  - brotli-bin=1.0.9=h5eb16cf_7
  - brotlipy=0.7.0=py310h1961e1f_1004
  - brunsli=0.1=h046ec9c_0
  - bzip2=1.0.8=h0d85af4_4
  - c-ares=1.18.1=h0d85af4_0
  - c-blosc2=2.1.1=h2699725_2
  - ca-certificates=2022.6.15=h033912b_0
  - cachetools=5.0.0=pyhd8ed1ab_0
  - cairo=1.16.0=h9e0e54b_1010
  - cartopy=0.20.2=py310he18ef84_4
  - certifi=2022.6.15=py310h2ec42d9_0
  - cffi=1.15.0=py310hcc37b68_0
  - cfitsio=4.1.0=h2c97ad1_0
  - charls=2.3.4=he49afe7_0
  - charset-normalizer=2.0.12=pyhd8ed1ab_0
  - click=8.1.3=py310h2ec42d9_0
  - click-completion=0.5.2=py310h2ec42d9_3
  - click-log=0.3.2=pyh9f0ad1d_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - cloudpickle=2.1.0=pyhd8ed1ab_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - colorcet=3.0.0=pyhd8ed1ab_0
  - cryptography=37.0.2=py310h52c3658_0
  - curl=7.83.1=h372c54d_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cytoolz=0.11.2=py310h1961e1f_2
  - dask-core=2022.5.2=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - debugpy=1.6.0=py310h9d931ec_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - docutils=0.15.2=py310h2ec42d9_3
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=0.8.3=pyhd8ed1ab_0
  - expat=2.4.8=h96cf925_0
  - fasteners=0.17.3=pyhd8ed1ab_0
  - fiona=1.8.21=py310h86461ec_1
  - flit-core=3.7.1=pyhd8ed1ab_0
  - flox=0.5.5=pyhd8ed1ab_0
  - folium=0.12.1.post1=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.0=h676cef8_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.33.3=py310h6c45266_0
  - freetype=2.10.4=h4cff582_1
  - freexl=1.0.6=h0d85af4_0
  - frozenlist=1.3.0=py310h1961e1f_1
  - fsspec=2022.5.0=pyhd8ed1ab_0
  - geocube=0.3.1=pyhd8ed1ab_0
  - geopandas=0.10.2=pyhd8ed1ab_1
  - geopandas-base=0.10.2=pyha770c72_1
  - geos=3.10.2=he49afe7_0
  - geotiff=1.7.1=had63758_1
  - gettext=0.19.8.1=hd1a6beb_1008
  - ghp-import=2.1.0=pyhd8ed1ab_0
  - giflib=5.2.1=hbcb3906_2
  - gitdb=4.0.9=pyhd8ed1ab_0
  - gitpython=3.1.27=pyhd8ed1ab_0
  - greenlet=1.1.2=py310h9d931ec_2
  - hdf4=4.2.15=hefd3b78_3
  - hdf5=1.12.1=nompi_ha60fbc9_104
  - holoviews=1.14.9=pyhd8ed1ab_0
  - hvplot=0.8.0=pyh6c4a22f_0
  - icu=69.1=he49afe7_0
  - idna=3.3=pyhd8ed1ab_0
  - imagecodecs=2022.2.22=py310h0d10b90_5
  - imageio=2.19.3=pyhcf75d05_0
  - imagesize=1.3.0=pyhd8ed1ab_0
  - importlib-metadata=4.11.4=py310h2ec42d9_0
  - importlib_metadata=4.11.4=hd8ed1ab_0
  - importlib_resources=5.7.1=pyhd8ed1ab_1
  - ipykernel=6.13.1=py310ha188af9_0
  - ipython=8.4.0=py310h2ec42d9_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.7.0=pyhd8ed1ab_0
  - jedi=0.18.1=py310h2ec42d9_1
  - jinja2=3.0.3=pyhd8ed1ab_0
  - jmespath=1.0.0=pyhd8ed1ab_0
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9e=h5eb16cf_1
  - json-c=0.16=h01d06f9_0
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter-book=0.12.3=pyhd8ed1ab_0
  - jupyter-cache=0.4.3=pyhd8ed1ab_0
  - jupyter-server-mathjax=0.2.5=pyhc268e32_0
  - jupyter-sphinx=0.3.2=pyhd8ed1ab_1
  - jupyter_client=7.3.1=pyhd8ed1ab_0
  - jupyter_core=4.10.0=py310h2ec42d9_0
  - jupyter_server=1.17.0=pyhd8ed1ab_0
  - jupyterlab=3.4.3=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_server=2.14.0=pyhd8ed1ab_0
  - jupyterlab_widgets=1.1.0=pyhd8ed1ab_0
  - jxrlib=1.1=h35c211d_2
  - kealib=1.4.14=ha22a8b1_3
  - kiwisolver=1.4.2=py310h6be76da_1
  - krb5=1.19.3=hb49756b_0
  - latexcodec=2.0.1=pyh9f0ad1d_0
  - lcms2=2.12=h577c468_0
  - lerc=3.0=he49afe7_0
  - libaec=1.0.6=he49afe7_0
  - libavif=0.10.1=h5eb16cf_0
  - libblas=3.9.0=14_osx64_openblas
  - libbrotlicommon=1.0.9=h5eb16cf_7
  - libbrotlidec=1.0.9=h5eb16cf_7
  - libbrotlienc=1.0.9=h5eb16cf_7
  - libcblas=3.9.0=14_osx64_openblas
  - libcurl=7.83.1=h372c54d_0
  - libcxx=14.0.4=hc203e6f_0
  - libdap4=3.20.6=h3e144a0_2
  - libdeflate=1.10=h0d85af4_0
  - libedit=3.1.20191231=h0678c8f_2
  - libev=4.33=haf1e3a3_1
  - libffi=3.4.2=h0d85af4_5
  - libgdal=3.4.3=h6474519_0
  - libgfortran=5.0.0=9_3_0_h6c81a4c_23
  - libgfortran5=9.3.0=h6c81a4c_23
  - libglib=2.70.2=hf1fb8c0_4
  - libiconv=1.16=haf1e3a3_0
  - libkml=1.3.0=h8fd9edb_1014
  - liblapack=3.9.0=14_osx64_openblas
  - libnetcdf=4.8.1=nompi_h6609ca0_102
  - libnghttp2=1.47.0=h942079c_0
  - libopenblas=0.3.20=openmp_hb3cd9ec_0
  - libpng=1.6.37=h7cec526_2
  - libpq=14.2=hea3049e_0
  - librttopo=1.1.0=hec60dd8_9
  - libsodium=1.0.18=hbcb3906_1
  - libspatialindex=1.9.3=he49afe7_4
  - libspatialite=5.0.1=hadde3e2_15
  - libssh2=1.10.0=h52ee1ee_2
  - libtiff=4.4.0=hfca7e8f_0
  - libwebp=1.2.2=h28dabe5_0
  - libwebp-base=1.2.2=h0d85af4_1
  - libxcb=1.13=h0d85af4_1004
  - libxml2=2.9.12=h7e28ab6_1
  - libzip=1.8.0=h8b0c345_1
  - libzlib=1.2.12=h6c3fc93_0
  - libzopfli=1.0.3=h046ec9c_0
  - linkify-it-py=1.0.3=pyhd8ed1ab_0
  - llvm-openmp=14.0.4=ha654fa7_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4-c=1.9.3=he49afe7_1
  - mapclassify=2.4.3=pyhd8ed1ab_0
  - markdown=3.3.7=pyhd8ed1ab_0
  - markdown-it-py=1.1.0=pyhd8ed1ab_0
  - markupsafe=2.1.1=py310h1961e1f_1
  - matplotlib-base=3.5.2=py310h4510841_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mdit-py-plugins=0.2.8=pyhd8ed1ab_0
  - mistune=0.8.4=py310he24745e_1005
  - msgpack-python=1.0.4=py310habb735a_0
  - multidict=6.0.2=py310h1961e1f_1
  - munch=2.5.0=py_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - myst-nb=0.13.2=pyhd8ed1ab_0
  - myst-parser=0.15.2=pyhd8ed1ab_0
  - nbclassic=0.3.7=pyhd8ed1ab_0
  - nbclient=0.5.13=pyhd8ed1ab_0
  - nbconvert=6.5.0=pyhd8ed1ab_0
  - nbconvert-core=6.5.0=pyhd8ed1ab_0
  - nbconvert-pandoc=6.5.0=pyhd8ed1ab_0
  - nbdime=3.1.1=pyhd8ed1ab_0
  - nbformat=5.4.0=pyhd8ed1ab_0
  - ncurses=6.3=h96cf925_1
  - nest-asyncio=1.5.5=pyhd8ed1ab_0
  - networkx=2.8.2=pyhd8ed1ab_0
  - notebook=6.4.11=pyha770c72_0
  - notebook-shim=0.1.0=pyhd8ed1ab_0
  - nspr=4.32=hcd9eead_1
  - nss=3.78=ha8197d3_0
  - numcodecs=0.9.1=py310hd4537e4_3
  - numpy=1.22.4=py310hed37afb_0
  - numpy_groupies=0.9.17=pyhd8ed1ab_0
  - odc-geo=0.1.3=pyhd8ed1ab_0
  - openjpeg=2.4.0=h6e7aa92_1
  - openssl=1.1.1o=hfe4f2af_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.4.2=py310h3099161_2
  - pandoc=2.18=h694c41f_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - panel=0.13.1=pyhd8ed1ab_0
  - param=1.12.1=pyh6c4a22f_0
  - parso=0.8.3=pyhd8ed1ab_0
  - partd=1.2.0=pyhd8ed1ab_0
  - patsy=0.5.2=pyhd8ed1ab_0
  - pcre=8.45=he49afe7_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.1.1=py310hb3240ae_1
  - pip=22.1.2=pyhd8ed1ab_0
  - pixman=0.40.0=hbcb3906_0
  - pooch=1.6.0=pyhd8ed1ab_0
  - poppler=22.04.0=h39497b0_0
  - poppler-data=0.4.11=hd8ed1ab_0
  - postgresql=14.2=he8fe76e_0
  - proj=9.0.0=h2364a93_1
  - prometheus_client=0.14.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.29=pyha770c72_0
  - psutil=5.9.1=py310h6c45266_0
  - pthread-stubs=0.4=hc929b4f_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pybtex=0.24.0=pyhd8ed1ab_2
  - pybtex-docutils=1.0.1=py310h2ec42d9_1
  - pycparser=2.21=pyhd8ed1ab_0
  - pyct=0.4.6=py_0
  - pyct-core=0.4.6=py_0
  - pydata-sphinx-theme=0.7.2=pyhd8ed1ab_0
  - pygments=2.12.0=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyproj=3.3.1=py310h6c09501_0
  - pyrsistent=0.18.1=py310h1961e1f_1
  - pyshp=2.3.0=pyhd8ed1ab_0
  - pysocks=1.7.1=py310h2ec42d9_5
  - python=3.10.4=h8b4d769_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.15.3=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytz=2022.1=pyhd8ed1ab_0
  - pyviz_comms=2.2.0=pyhd8ed1ab_0
  - pywavelets=1.3.0=py310h7f5fb2b_1
  - pyyaml=6.0=py310h1961e1f_4
  - pyzmq=23.0.0=py310h85fb675_0
  - rasterio=1.2.10=py310h7a5eec6_5
  - readline=8.1=h05e3726_0
  - requests=2.27.1=pyhd8ed1ab_0
  - rioxarray=0.11.1=pyhd8ed1ab_0
  - rtree=1.0.0=py310had9ce37_1
  - s3fs=2022.5.0=pyhd8ed1ab_0
  - scikit-image=0.19.2=py310hdd25497_0
  - scikit-learn=1.1.1=py310hfc06b38_0
  - scipy=1.8.1=py310h1f9c157_0
  - seaborn=0.11.2=hd8ed1ab_0
  - seaborn-base=0.11.2=pyhd8ed1ab_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=62.3.2=py310h2ec42d9_0
  - shapely=1.8.2=py310h6d09efd_1
  - shellingham=1.4.0=pyh44b312d_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=3.0.5=pyh44b312d_0
  - snappy=1.1.9=h6e38e02_1
  - sniffio=1.2.0=py310h2ec42d9_3
  - snowballstemmer=2.2.0=pyhd8ed1ab_0
  - snuggs=1.4.7=py_0
  - soupsieve=2.3.1=pyhd8ed1ab_0
  - sphinx=4.5.0=pyh6c4a22f_0
  - sphinx-book-theme=0.1.10=pyhd8ed1ab_1
  - sphinx-comments=0.0.3=pyh9f0ad1d_0
  - sphinx-copybutton=0.5.0=pyhd8ed1ab_0
  - sphinx-external-toc=0.2.4=pyhd8ed1ab_0
  - sphinx-jupyterbook-latex=0.4.6=pyhd8ed1ab_0
  - sphinx-multitoc-numbering=0.1.3=pyhd8ed1ab_0
  - sphinx-panels=0.6.0=pyhd8ed1ab_0
  - sphinx-thebe=0.1.2=pyhd8ed1ab_0
  - sphinx-togglebutton=0.3.1=pyhd8ed1ab_0
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-bibtex=2.4.2=pyhd8ed1ab_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd8ed1ab_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd8ed1ab_2
  - sqlalchemy=1.4.36=py310h6c45266_0
  - sqlite=3.38.5=hd9f0692_0
  - stack_data=0.2.0=pyhd8ed1ab_0
  - statsmodels=0.13.2=py310h1bbcd0e_0
  - terminado=0.15.0=py310h2ec42d9_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tifffile=2022.5.4=pyhd8ed1ab_0
  - tiledb=2.8.3=hf17dc58_1
  - tinycss2=1.1.1=pyhd8ed1ab_0
  - tk=8.6.12=h5dbffcc_0
  - toolz=0.11.2=pyhd8ed1ab_0
  - tornado=6.1=py310h1961e1f_3
  - tqdm=4.64.0=pyhd8ed1ab_0
  - traitlets=5.2.1.post0=pyhd8ed1ab_0
  - typing-extensions=4.2.0=hd8ed1ab_1
  - typing_extensions=4.2.0=pyha770c72_1
  - tzcode=2022a=h5eb16cf_0
  - tzdata=2022a=h191b570_0
  - uc-micro-py=1.0.1=pyhd8ed1ab_0
  - unicodedata2=14.0.0=py310h1961e1f_1
  - urllib3=1.26.9=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - websocket-client=1.3.2=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - widgetsnbextension=3.6.0=py310h2ec42d9_0
  - wrapt=1.14.1=py310h6c45266_0
  - xarray=2022.3.0=pyhd8ed1ab_0
  - xerces-c=3.2.3=h6564042_4
  - xorg-libxau=1.0.9=h35c211d_0
  - xorg-libxdmcp=1.1.3=h35c211d_0
  - xyzservices=2022.4.0=pyhd8ed1ab_0
  - xz=5.2.5=haf1e3a3_1
  - yaml=0.2.5=h0d85af4_2
  - yarl=1.7.2=py310h1961e1f_2
  - zarr=2.11.3=pyhd8ed1ab_0
  - zeromq=4.3.4=he49afe7_1
  - zfp=0.5.5=h4a89273_8
  - zipp=3.8.0=pyhd8ed1ab_0
  - zlib=1.2.12=h6c3fc93_0
  - zlib-ng=2.0.6=hac89ed1_0
  - zstd=1.5.2=ha9df2e0_1
  - pip:
    - gdal==3.4.3
    - itslivetools==0.0.2
prefix: /Users/emarshall/miniconda3/envs/itslivetools_env
